apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../dashboard
  - ../../keycloak

configMapGenerator:
  - name: ml-platform-admin-configmap
    namespace: ml-platform-system
    behavior: replace
    files:
      - prod.yaml=dashboard-config.yaml

patches:
  - target:
      kind: Service
      name: ml-platform-admin-web
      namespace: ml-platform-system
      version: v1
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 32000  # you can change the nodePort value
  - target:
      kind: Service
      name: openfga-api
      namespace: ml-platform-system
      version: v1
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081  # GRPC port
      - op: add
        path: /spec/ports/1/nodePort
        value: 30080  # HTTP port
      - op: add
        path: /spec/ports/2/nodePort
        value: 30082  # Playground port
